package view;

import model.GerenciarProduto;
import model.Produto;
import java.awt.Component;
import javax.swing.JDialog;
import javax.swing.JOptionPane;


public class CadastroDeProdutoGUI extends javax.swing.JFrame {

    /**
     * Creates new form CadastroDeProdutoGUI
     */
    GerenciarProduto ge;
    Produto e;
    public CadastroDeProdutoGUI() {
        initComponents();

        ge = new GerenciarProduto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        panelProduto = new javax.swing.JPanel();
        ProdNom = new javax.swing.JLabel();
        ProdQTD = new javax.swing.JLabel();
        ProdCom = new javax.swing.JLabel();
        ProdVen = new javax.swing.JLabel();
        buttonCadastrar = new javax.swing.JButton();
        buttonApresentar = new javax.swing.JButton();
        textNomeProduto = new javax.swing.JTextField();
        textQtdProduto = new javax.swing.JTextField();
        textValorCompra = new javax.swing.JTextField();
        buttonLimpar = new javax.swing.JButton();
        textValorVenda = new javax.swing.JFormattedTextField();
        textCodProduto = new javax.swing.JFormattedTextField();
        ProdCod = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Produto");
        setBackground(java.awt.Color.lightGray);

        panelProduto.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastrar novo Produto"));
        panelProduto.setToolTipText("Cadastro de novos produtos ");

        ProdNom.setText("Nome do Produto");
        ProdNom.setToolTipText("Nome do Produto para cadastrar");

        ProdQTD.setText("Quantidade");
        ProdQTD.setToolTipText("Quantidade do produto em estoque");

        ProdCom.setText("Valor de Compra");
        ProdCom.setToolTipText("Custo de aquisição do produto");

        ProdVen.setText("Valor de Venda");
        ProdVen.setToolTipText("Valor para venda do produto");

        buttonCadastrar.setText("Cadastrar");
        buttonCadastrar.setToolTipText("Cadastra o produto no estoque");
        buttonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarActionPerformed(evt);
            }
        });

        buttonApresentar.setText("Ver Estoque");
        buttonApresentar.setToolTipText("Mostra os itens salvos no estoque");
        buttonApresentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonApresentarActionPerformed(evt);
            }
        });

        textValorCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textValorCompraActionPerformed(evt);
            }
        });

        buttonLimpar.setText("Limpar");
        buttonLimpar.setToolTipText("Limpa todos os campos de texto");
        buttonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimparActionPerformed(evt);
            }
        });

        textValorVenda.setToolTipText("");

        textCodProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCodProdutoActionPerformed(evt);
            }
        });

        ProdCod.setText("Codigo do Produto");
        ProdCod.setToolTipText("Código de identificação do produto");

        javax.swing.GroupLayout panelProdutoLayout = new javax.swing.GroupLayout(panelProduto);
        panelProduto.setLayout(panelProdutoLayout);
        panelProdutoLayout.setHorizontalGroup(
            panelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProdQTD)
                    .addComponent(ProdCom)
                    .addComponent(ProdVen)
                    .addComponent(ProdCod)
                    .addComponent(ProdNom)
                    .addGroup(panelProdutoLayout.createSequentialGroup()
                        .addComponent(buttonLimpar)
                        .addGap(18, 18, 18)
                        .addComponent(buttonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(textValorCompra, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textQtdProduto, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textNomeProduto, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textCodProduto, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textValorVenda)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelProdutoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(buttonApresentar, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelProdutoLayout.setVerticalGroup(
            panelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProdutoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProdCod, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(textCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProdNom, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(textNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProdQTD, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(textQtdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(panelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProdCom, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(textValorCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(panelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProdVen, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(textValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(panelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCadastrar)
                    .addComponent(buttonApresentar)
                    .addComponent(buttonLimpar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelProduto.getAccessibleContext().setAccessibleDescription("Cadastro de novos produtos");

        getAccessibleContext().setAccessibleDescription("Cadastro de novos produtos");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Botão cadastrar pressionado
    private void buttonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarActionPerformed
        try {
            e = new Produto();
            e.setCodigoProduto(Integer.parseInt(textCodProduto.getText()));
            e.setNomeProduto(textNomeProduto.getText());
            e.setValor(Float.parseFloat(textValorCompra.getText()));
            e.setPrecoProduto(Float.parseFloat(textValorVenda.getText()));
            e.setQtdProduto(Integer.parseInt(textQtdProduto.getText()));
            
            //Envia pedido para cadastro de Uusuário
            if(ge.adicionarProduto(e)){
                //Exibe mensagem de cadastro realizado com sucesso
                Component frame = null;
                JOptionPane.showMessageDialog(frame, "Produto cadastrado com sucesso!");

                //Simula clique no botão limpar para limpar o formulário
                buttonLimpar.doClick();
                
                //Criando nova instância para zerar referências ao produto que
                //acabou de ser adicionado na lista de produto
                e = new Produto();
            }
            else {
                JOptionPane optionPane = new JOptionPane("Erro! Confira os dados e tente novamente!", 
                        JOptionPane.ERROR_MESSAGE);    
                JDialog dialog = optionPane.createDialog("Erro");
                dialog.setAlwaysOnTop(true);
                dialog.setVisible(true);
            }
            
            
        
        //Verificação geral de erros/exceções, com mensagem de retorno ao usuário               
        } catch (Exception e) {
            JOptionPane optionPane = new JOptionPane("Erro! Confira os dados e tente novamente!", 
                    JOptionPane.ERROR_MESSAGE);    
            JDialog dialog = optionPane.createDialog("Erro");
            dialog.setAlwaysOnTop(true);
            dialog.setVisible(true);
        }
 
    }//GEN-LAST:event_buttonCadastrarActionPerformed

    //Botão apresentar produtos pressionado   
    private void buttonApresentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonApresentarActionPerformed
        
        //Abre a tela Gerenciar Produtos e encerra a atual
        GerenciarEstoqueGUI gerProd = new GerenciarEstoqueGUI();
        gerProd.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonApresentarActionPerformed

    //Botão limpar pressionado
    private void buttonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimparActionPerformed
        
        //Zera todos os campos
        textNomeProduto.setText("");
        textQtdProduto.setText("");
        textValorCompra.setText("");
        textValorVenda.setText("");
        textCodProduto.setText("");
        
    }//GEN-LAST:event_buttonLimparActionPerformed

    private void textCodProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCodProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCodProdutoActionPerformed

    private void textValorCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textValorCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textValorCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroDeProdutoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroDeProdutoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroDeProdutoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroDeProdutoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroDeProdutoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ProdCod;
    private javax.swing.JLabel ProdCom;
    private javax.swing.JLabel ProdNom;
    private javax.swing.JLabel ProdQTD;
    private javax.swing.JLabel ProdVen;
    private javax.swing.JButton buttonApresentar;
    private javax.swing.JButton buttonCadastrar;
    private javax.swing.JButton buttonLimpar;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel panelProduto;
    private javax.swing.JFormattedTextField textCodProduto;
    private javax.swing.JTextField textNomeProduto;
    private javax.swing.JTextField textQtdProduto;
    private javax.swing.JTextField textValorCompra;
    private javax.swing.JFormattedTextField textValorVenda;
    // End of variables declaration//GEN-END:variables
}
